### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by BrunoVernay** [flathub/org.musescore.MuseScore#123]
When starting the application I get this crash about once every 3 or 4 launch:
`/usr/include/c++/13.2.0/array:211: constexpr const std::array<_Tp, _Nm>::value_type& std::array<_Tp, _Nm>::operator[](size_type) const [with _Tp = mu::engraving::PropertyValue; long unsigned int _Nm = 1433; const_reference = const mu::engraving::PropertyValue&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.`

**Comment by hfiguiere** [comment]
it's a bug in upstream code because they build without CXX_ASSERTIONS when they test.

Without a stack trace it's hard to pinpoint.

**Comment by hfiguiere** [comment]
```
Thread 1 "mscore" received signal SIGABRT, Aborted.
0x00007ffff50a3e14 in __pthread_kill_implementation () from /usr/lib/x86_64-linux-gnu/libc.so.6
(gdb) where
#0  0x00007ffff50a3e14 in __pthread_kill_implementation () at /usr/lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff5051dce in raise () at /usr/lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff503983f in abort () at /usr/lib/x86_64-linux-gnu/libc.so.6
#3  0x00007ffff52ececd in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x0000555556443427 in std::array<mu::engraving::PropertyValue, 1433ul>::operator[](unsigned long) const
    (this=<optimized out>, __n=18446744073709551609) at /usr/include/c++/13.2.0/array:208
#5  std::array<mu::engraving::PropertyValue, 1433ul>::operator[](unsigned long) const (__n=18446744073709551609, this=<optimized out>)
    at /usr/include/c++/13.2.0/array:208
#6  mu::engraving::MStyle::value(mu::engraving::MSQE_Sid::Sid) const (this=<optimized out>, idx=idx@entry=-7)
    at /run/build/musescore/src/engraving/style/style.cpp:51
#7  0x00005555560eb090 in mu::engraving::MStyle::styleV(mu::engraving::MSQE_Sid::Sid) const (idx=-7, this=<optimized out>)
    at /run/build/musescore/src/engraving/style/style.h:52
#8  mu::engraving::EngravingObject::styleValue(mu::engraving::Pid, mu::engraving::MSQE_Sid::Sid) const
    (this=this@entry=0x55555a06e920, pid=<optimized out>, sid=-7) at /run/build/musescore/src/engraving/dom/engravingobject.cpp:768
#9  0x00005555560eb51b in mu::engraving::EngravingObject::initElementStyle(std::vector<mu::engraving::StyledProperty, std::allocator<mu::engraving::StyledProperty> > const*) (this=this@entry=0x55555a06e920, ss=ss@entry=0x555558c75aa0 <mu::engraving::pedalStyle>)
    at /run/build/musescore/src/engraving/dom/engravingobject.cpp:324
#10 0x00005555561f5843 in mu::engraving::Pedal::Pedal(mu::engraving::EngravingItem*) (this=this@entry=0x55555a06e920, parent=parent@entry=0x55555964bfd0)
    at /run/build/musescore/src/engraving/dom/pedal.cpp:105
#11 0x0000555556a409ee in std::_Construct<mu::engraving::Pedal, mu::engraving::compat::DummyElement*>(mu::engraving::Pedal*, mu::engraving::compat::DummyElement*&&) (__p=0x55555a06e920) at /usr/include/c++/13.2.0/bits/stl_construct.h:109
#12 std::allocator_traits<std::allocator<void> >::construct<mu::engraving::Pedal, mu::engraving::compat::DummyElement*>(std::allocator<void>&, mu::engraving::Pedal*, mu::engraving::compat::DummyElement*&&) (__p=0x55555a06e920) at /usr/include/c++/13.2.0/bits/alloc_traits.h:660
#13 std::_Sp_counted_ptr_inplace<mu::engraving::Pedal, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<mu::engraving::compat::DummyElement*>(std::allocator<void>, mu::engraving::compat::DummyElement*&&) (__a=..., this=0x55555a06e910)
    at /usr/include/c++/13.2.0/bits/shared_ptr_base.h:604
#14 std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<mu::engraving::Pedal, std::allocator<void>, mu::engraving::compat::DummyElement*>(mu::engraving::Pedal*&, std::_Sp_alloc_shared_tag<std::allocator<void> >, mu::engraving::compat::DummyElement*&&)
    (__a=..., __p=@0x7fffffffce50: 0x0, this=0x7fffffffce58) at /usr/include/c++/13.2.0/bits/shared_ptr_base.h:971
#15 std::__shared_ptr<mu::engraving::Pedal, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<void>, mu::engraving::compat::DummyElement*>(std::_Sp_alloc_shared_tag<std::allocator<void> >, mu::engraving::compat::DummyElement*&&) (__tag=..., this=0x7fffffffce50)
    at /usr/include/c++/13.2.0/bits/shared_ptr_base.h:1712
#16 std::shared_ptr<mu::engraving::Pedal>::shared_ptr<std::allocator<void>, mu::engraving::compat::DummyElement*>(std::_Sp_alloc_shared_tag<std::allocator<v
```

-7 as an index

**Comment by hfiguiere** [comment]
Upstream likely https://github.com/musescore/MuseScore/issues/20555

**Comment by helkaluin** [comment]
Is it possible for Flathub to built it without CXX_ASSERTIONS in the meantime? As it is, this Flatpak package simply isn't usable with the frequent crashes at launch.

**Comment by hfiguiere** [comment]
and have it actually crash instead? Because that's what would happen.

**Comment by hfiguiere** [comment]
there are almost 5 dupes for it upstream.
